# Generated by Django 6.1 on 2026-09-06 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='bucket_covers/')),
                ('description', models.TextField(blank=True)),
                ('why_statement', models.TextField(blank=True, help_text='Why do you want to accomplish this?')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', '🟢 Low'), ('Medium', '🟡 Medium'), ('High', '🔴 High')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Dream', '💭 Dream'), ('Planned', '📋 Planned'), ('Preparing', '🛠️ Preparing'), ('InProgress', '🚶 In Progress'), ('GonnaComplete', '🔥 Gonna Complete'), ('Completed', '🎉 Completed')], default='Dream', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('completion_date', models.DateField()),
                ('mood', models.CharField(choices=[('Happy', '😊 Happy'), ('Excited', '🥰 Excited'), ('Amazing', '🤩 Amazing'), ('Peaceful', '😌 Peaceful'), ('Emotional', '🥹 Emotional'), ('Proud', '😎 Proud'), ('Satisfied', '🌱 Satisfied')], default='Happy', max_length=20)),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='wishwell.bucketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memories',
            },
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memory_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wishwell.memory')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.AddField(
            model_name='bucketitem',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='wishwell.shelf'),
        ),
    ]
