# Generated by Django 6.1 on 2026-09-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishwell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowprogress',
            options={'verbose_name': 'Goal Progress', 'verbose_name_plural': 'Goal Progresses'},
        ),
        migrations.AddField(
            model_name='shelf',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucketitem',
            name='status',
            field=models.CharField(choices=[('Dream', '💭 Dream'), ('Goal', '🥅 Goal'), ('Planned', '📋 Planned'), ('Preparing', '🛠️ Preparing'), ('InProgress', '🚶 In Progress'), ('GonnaComplete', '🔥 Gonna Complete'), ('Completed', '🎉 Completed')], default='Dream', max_length=20),
        ),
    ]
