# Generated by Django 6.1 on 2026-09-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishwell', '0002_alter_flowprogress_options_shelf_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bucket_items/'),
        ),
    ]
